trigger: none

pool: default

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building..."

    - script: echo "Deploying..."

    - task: XplatGenerateReleaseNotes@4
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)/releaseNotes.md'
        templateLocation: 'File'
        templatefile: '$(Build.SourcesDirectory)/templates/releaseNotesTemplate.md'
        dumpPayloadToConsole: True
        dumpPayloadToFile: false
        replaceFile: True
        getParentsAndChildren: True
        getAllParents: True
        getIndirectPullRequests: False
        stopOnError: False
        considerPartiallySuccessfulReleases: False
        checkForManuallyLinkedWI: False
        wiqlFromTarget: 'WorkItems'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'ReleaseNotes'
        publishLocation: 'pipeline'
    
    - task: WikiUpdaterTask@2
      inputs:
        repo: 'https://dev.azure.com/ShruBookStore/Migration%20work/_git/ReleaseNotes'
        branch: 'main'
        filename: 'Root-page/ReleaseVersions.md'
        replaceFile: false
        appendToFile: true
        dataIsFile: true
        sourceFile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'
        message: 'Automatic commit from pipeline'
        gitname: 'pipeline'
        gitemail: 'nitanshusingh55@gmail.com'
        useAgentToken: true
        localpath: '$(System.DefaultWorkingDirectory)\repo'
        RetryMode: 'Pull'